### ISSUE TITLE
modify thresholds for K17+ and K17-

### ISSUE THREAD

**Issue by kaczmarj** [kaczmarj/tumor-microenvironment-analysis#1]
from meeting on august 27, 2021 at 8:30am, we would like to call a tumor patch K17 negative if there is less than 10% brown stain. if there is >= 10% brown stain, the tumor patch should be called K17 positive.

it would also be helpful to have a function that plots only the outline of the patches on top of the slide roi. this way we can verify if the thresholding makes sense.

**Comment by Shauqi** [comment]
For threshold selection, for Tumor the threshold should be more than >=5% and for K17p threshold it should be >= 40%

**Comment by kaczmarj** [comment]
fixed by https://github.com/kaczmarj/tumor-microenvironment-analysis/commit/9f72e551ebbf32d3c51ef646fad472311db017ca
