### ISSUE TITLE
implement normalization methods

### ISSUE THREAD

**Issue by kaczmarj** [kaczmarj/tumor-microenvironment-analysis#2]
implement the three normalization methods from our google doc

**Comment by Shauqi** [comment]
For normalization, we can consider each patch's (in the ROI) center point and calculate distance from the tumor boundary as we did for the lattice point of each cell. calculating the middle point's (of the patch) distance from the Tumor boundary we can find out which patches are impacted by tumor boundary. We can get the number of patches impacted by M+ and the number of patches impacted by M- and finally, we can use these numbers to normalize the CDFs.
